version: "3.4"

services:
  php-custom:
    image: php-custom
    environment:
      - TEST_SERVER_HOST
    build: .
    command: composer test
    #network_mode: host
    ports:
      - 80:80
    tty: true
    volumes:
      - ./:/var/www/html
