version: "3.4"

services:
  php-custom:
    image: php-custom
    environment:
      - TEST_SERVER_HOST
    build: .
    # extra_hosts:
    #   - test-server:test-server
    command: composer test
    network_mode: host
    tty: true
    volumes:
      - ./:/var/www/html
