version: "3.4"

services:
  php-custom:
    image: php-custom
    network_mode: host
    build: .
    command: composer test
    tty: true
    extra_host:
      - "httpd:0.0.0.0"
    volumes:
      - ./:/var/www/html
