version: "3.4"

services:
  php-custom:
    image: nginx
    network_mode: container:${{job.container.id}}
    build: .
    #command: composer test
    tty: true
    volumes:
      - ./:/var/www/html
