version: "3.4"

services:
  php-custom:
    image: alpine
    networks:
      - network1
    build: .
    command: nslookup test-servere
    tty: true

networks:
  network1:
    name: $NETWORK
    external: true
