version: "3.4"

services:
  php-custom:
    image: nginx
    network_mode: container:derserver
    extra_hosts:
    - "host.docker.internal:host-gateway"
    build: .
    #command: composer test
    tty: true
    volumes:
      - ./:/var/www/html
