name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      test-server:
        image: httpd:latest
        ports:
          - 80:80
        # set health checks to wait until postgres has started
        #options: >-
        #  --health-cmd pg_isready
        #  --health-interval 10s
        #  --health-timeout 5s
        #  --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install packages
        run: |
          apt-get update
          apt-get install --yes dnsutils docker docker-compose-plugin
          
      - name: Check if hostname is resolved successfully
        run: nslookup test-server
        
      - name: Docker Compose
        run: docker compose -f ./php/docker-compose.ci.yml up --detach
