name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      httpd:
        image: httpd
        ports:
          - 80:80

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Health Check
        run: sleep 5 && curl -v http://localhost:80/manifest.json
        
      - name: Logging job
        run: echo "${{ toJSON(job) }}"

      - name: Exporting service container id
        run: export HTTPD_ID=${{ job.services.httpd.id }}

      - name: Exporting service container network
        run: export NETWORK_ID=${{ job.services.httpd.network }}
        
      - name: Docker Compose
        run: docker-compose -e HTTPD_ID=$HTTPD_ID -f ./php/docker-compose.ci.yml up --detach

