name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres_db
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        # set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Docker Info
        run: docker ps -a

      - name: Test
        run: dig postgres

      - name: Install PostgreSQL client   
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Install database
        run: |
          psql -h postgres -d postgres_db -U postgres_user -c  'CREATE DATABASE rolling_test;' -U postgres
          
      #- name: Logging job
      #  run: docker inspect --format '{{ .NetworkSettings.Networks.${{ job.services.httpd.network }}.IPAddress }}' ${{ job.services.httpd.id }}
        
      #- name: Docker Compose
      #  run: docker-compose -f ./php/docker-compose.ci.yml up --detach
