name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 80:80

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      #- name: Health Check
      #  run: sleep 5 && curl 0.0.0.0:80

      - name: Docker Info
        run: docker ps -a

      - name: Test
        run: dig postgres

      - name: Install PostgreSQL client   
        run: |
          apt-get update
          apt-get install --yes postgresql-client

      - name: Install database
        run: |
          psql -h postgres -d postgres_db -U postgres_user -c  'CREATE DATABASE rolling_test;' -U postgres
          
      #- name: Logging job
      #  run: docker inspect --format '{{ .NetworkSettings.Networks.${{ job.services.httpd.network }}.IPAddress }}' ${{ job.services.httpd.id }}
        
      #- name: Docker Compose
      #  run: docker-compose -f ./php/docker-compose.ci.yml up --detach
