name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    #container: ubuntu
    services:
      test-server:
        image: httpd:latest
        ports:
          - 80:80

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Install dnsutils and curl
      #  run: |
      #    apt-get update
      #    apt-get install --yes dnsutils curl

      #- name: Check if hostname is resolved successfully
      #  run: nslookup test-server

      #- name: Download docker
      #  run: curl -fsSL https://get.docker.com -o get-docker.sh

      #- name: Install docker
      #  run: sh ./get-docker.sh

      - name: Create env file
        run: |
          touch .env
          echo "NETWORK=${{ job.container.network }}" > .env
          cat .env

      - name: Docker Compose
        run: docker compose --env-file .env -f ./php/docker-compose.ci.yml up --exit-code-from php-custom

      #- name: docker ps -a
      #  run: docker ps -a

      #- name: docker compose container
      #  run: docker inspect php-php-custom-1
