name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    #container: ubuntu
    services:
      test-server:
        image: httpd:latest
        #env:
        #  POSTGRES_DB: postgres_db
        #  POSTGRES_PASSWORD: postgres_password
        #  POSTGRES_PORT: 5432
        #  POSTGRES_USER: postgres_user
        ports:
          - 80:80
        # set health checks to wait until postgres has started
        #options: >-
        #  --health-cmd pg_isready
        #  --health-interval 10s
        #  --health-timeout 5s
        #  --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Docker Info
      #  run: docker ps -a

      - name: Install PostgreSQL client   
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client dnsutils
          
      - name: Test
        run: dig test-server

      #- name: Logging job
      #  run: docker inspect --format '{{ .NetworkSettings.Networks.${{ job.services.httpd.network }}.IPAddress }}' ${{ job.services.httpd.id }}
        
      - name: Docker Compose
        run: docker-compose -f ./php/docker-compose.ci.yml up --detach
