name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      httpd:
        image: httpd
        ports:
          - 80:80

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Health Check
        run: sleep 5 && curl -v http://localhost:80/manifest.json
        
      - name: Docker Compose
        run: docker-compose -f ./php/docker-compose.ci.yml up --exit-code-from php-custom

      - name: Docker Inspect
        run: docker inspect
