name: Runner
on: push

jobs:
  runner-job:
    runs-on: ubuntu-latest
    services:
      test-server:
        image: httpd
        ports:
          - 80:80

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Health Check
        run: cat /etc/hosts
        env:
          THEIP: $(docker inspect --format '{{ .NetworkSettings.Networks.${{ job.services.httpd.network }}.IPAddress }}' ${{ job.services.httpd.id }})
        
      #- name: Logging job
      #  run: docker inspect --format '{{ .NetworkSettings.Networks.${{ job.services.httpd.network }}.IPAddress }}' ${{ job.services.httpd.id }}
        
      #- name: Docker Compose
      #  run: export HTTPD_ID=${{ job.services.httpd.id }} && export HTTPD_IP=$(docker inspect --format '{{ .NetworkSettings.Networks.${{ job.services.httpd.network }}.IPAddress }}' ${{ job.services.httpd.id }}) && docker-compose -f ./php/docker-compose.ci.yml up --detach

